## Docker file 
 ##docker build --build-arg artifactId="config-server" --build-arg version=0.0.1-SNAPSHOT .

FROM alpine as builder
FROM maven:3.2-jdk-8 as build
ARG version
WORKDIR /opt/config-server/
COPY . /opt/config-server/
RUN mvn clean package "-DbuildId=${version}
#CMD ls -l /opt/config-server/target


 FROM openjdk:8-jre-alpine
 ARG artifactId
 ARG version
 ENV artifact=${artifactId}-${version}.jar
 EXPOSE 8888
 WORKDIR /opt/config-server/
 COPY --from=build /opt/config-server/target/${artifact} .
 RUN mkdir -p /opt/config-repo
 CMD java -jar $artifact --eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
